-- Write SQL queries to perform the following tasks using the Sakila database:

-- 1. List the number of films per category.

SELECT category.name AS category, COUNT(film_category.film_id) as films_count
FROM category
JOIN film_category USING (category_id)
GROUP BY category;

-- 2. Retrieve the store ID, city, and country for each store.

SELECT store.store_id, city.city, country.country
FROM store 
JOIN address USING (address_id)
JOIN city USING (city_id)
JOIN country USING (country_id);

-- 3. Calculate the total revenue generated by each store in dollars.

SELECT store.store_id, SUM(payment.amount) 
FROM store
JOIN staff USING (store_id)
JOIN payment USING (staff_id)
GROUP BY store.store_id;

SELECT store.store_id, SUM(payment.amount) as total_amout
FROM store
JOIN inventory USING (store_id)
JOIN rental USING (inventory_id)
JOIN payment USING (rental_id)
GROUP BY store.store_id;

-- 4. Determine the average running time of films for each category.

SELECT category.name, AVG(film.length) as ave_run_time 
FROM film
JOIN film_category USING (film_id)
JOIN category USING (category_id)
GROUP BY category_id;

-- Bonus:
-- Identify the film categories with the longest average running time.
-- Display the top 10 most frequently rented movies in descending order.
-- Determine if "Academy Dinosaur" can be rented from Store 1.
-- Provide a list of all distinct film titles, along with their availability status in the inventory. Include a column indicating whether each title is 'Available' or 'NOT available.' Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."

-- Here are some tips to help you successfully complete the lab:

-- Tip 1: 
-- This lab involves joins with multiple tables, which can be challenging. Take your time and follow the steps we discussed in class:

-- Make sure you understand the relationships between the tables in the database. This will help you determine which tables to join and which columns to use in your joins.
-- Identify a common column for both tables to use in the ON section of the join. If there isn't a common column, you may need to add another table with a common column.
-- Decide which table you want to use as the left table (immediately after FROM) and which will be the right table (immediately after JOIN).
-- Determine which table you want to include all records from. This will help you decide which type of JOIN to use. If you want all records from the first table, use a LEFT JOIN. If you want all records from the second table, use a RIGHT JOIN. If you want records from both tables only where there is a match, use an INNER JOIN.
-- Use table aliases to make your queries easier to read and understand. This is especially important when working with multiple tables.

-- Write the query

-- Tip 2: 
-- Break down the problem into smaller, more manageable parts. For example, you might start by writing a query to retrieve data from just two tables before adding additional tables to the join. Test your queries as you go, and check the output carefully to make sure it matches what you expect. This process takes time, so be patient and go step by step to build your query incrementally.